# Generated by Django 4.0.5 on 2022-06-22 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Professor',
            new_name='Disciplina',
        ),
    ]
